- name: Setup development environment
  hosts: localhost
  become: no
  vars:
    lazygit_repo: "https://github.com/jesseduffield/lazygit"
    font_package: "font-fira-code-nerd-font"
    python_env_name: "nvim"
    python_version: "3.9.0"
  tasks:
    - name: Detect operating system
      ansible.builtin.set_fact:
        is_linux: "{{ ansible_system == 'Linux' }}"
        is_macos: "{{ ansible_system == 'Darwin' }}"

    - name: Install packages on Linux
      ansible.builtin.apt:
        name:
          - fontconfig
          - npm
          - xclip
          - lua5.3
          - fd-find
          - build-essential
          - zlib1g-dev
          - libffi-dev
          - libssl-dev
          - libbz2-dev
          - libreadline-dev
          - libsqlite3-dev
          - liblzma-dev
          - libncurses-dev
          - tk-dev
        update_cache: yes
      when: is_linux
      become: yes

    - name: Install packages on macOS
      ansible.builtin.homebrew:
        name:
          - lazygit
          - fd
          - npm
      when: is_macos

    - name: Install font on macOS
      ansible.builtin.homebrew_cask:
        name: "{{ font_package }}"
      when: is_macos

    - name: Remove previous version
      ansible.builtin.file:
        name: "{{ ansible_env.HOME }}/.pyenv"
        state: absent

    - name: Ensure pyenv and virtualenv are installed
      ansible.builtin.shell: |
        if ! command -v pyenv &> /dev/null; then
          curl https://pyenv.run | bash
        fi
      args:
        executable: /bin/bash
      register: pyenv_installed

    - name: Create and activate Python virtualenv for Vimspector
      ansible.builtin.shell: |
        export PATH="$HOME/.pyenv/bin:$PATH"
        eval "$(pyenv init --path)"
        eval "$(pyenv init -)"
        eval "$(pyenv virtualenv-init -)"
        pyenv install -s "{{ python_version }}" 
        pyenv global "{{ python_version }}"
        pyenv virtualenv "{{ python_version }}" "{{ python_env_name }}"
        pyenv activate "{{ python_env_name }}"
        pip install pynvim
        pyenv deactivate
      args:
        executable: /bin/bash
      when: pyenv_installed.failed == true
      
    - name: Install LazyGit on Linux
      ansible.builtin.shell: |
        if ! command -v lazygit &> /dev/null; then
          LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | grep -Po '"tag_name": *"v\K[^"]*')
          curl -Lo /tmp/lazygit.tar.gz "{{ lazygit_repo }}/releases/download/v${LAZYGIT_VERSION}/lazygit_${LAZYGIT_VERSION}_Linux_{{ ISA }}.tar.gz"
          tar xf /tmp/lazygit.tar.gz -C /usr/local/bin/
          rm -rf /tmp/lazygit.tar.gz
        fi
      when: is_linux
      become: yes
      args:
        executable: /bin/bash

    - name: Add alias for nvim if not present
      ansible.builtin.lineinfile:
        path: "{{ item }}" 
        line: "alias vim='nvim'"
        state: present
      loop:
        - ~/.zshrc
        - ~/.bashrc

    - name: Add pyenv to rc
      ansible.builtin.blockinfile:
        path: "{{ item }}" 
        block: |
          export PATH="$HOME/.pyenv/bin:$PATH"
          eval "$(pyenv init --path)"
          eval "$(pyenv init -)"
          eval "$(pyenv virtualenv-init -)"
        state: present
      loop:
        - ~/.zshrc
        - ~/.bashrc

    - name: create font cache
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.fonts"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        state: directory 
      tags: ["font"]

    - name: Install FiraCode nerd font
      ansible.builtin.shell: |
        curl -Lo /tmp/firacode.zip "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/FiraCode.zip"
        unzip /tmp/firacode.zip -d ~/.fonts/
        fc-cache -fv
      when: is_linux
      args:
        executable: /bin/bash
      tags: ["font"]

