---
- name: Install latest Go on Ubuntu
  hosts: all
  become: yes
  vars:
    go_download_base: "https://go.dev/dl/"
    go_install_dir: "/usr/local"
  tasks:
    - name: Get latest Go version
      ansible.builtin.uri:
        url: "https://go.dev/VERSION?m=text"
        return_content: yes
      register: go_version_response

    - name: Set Go version facts
      set_fact:
        go_version_string: "{{ go_version_response.content.splitlines()[0] }}"
        go_tarball: "{{ go_version_response.content.splitlines()[0] }}.linux-{{ ISA }}.tar.gz"

    - name: link
      ansible.builtin.debug:
        var: go_tarball

    - name: Download Go tarball
      ansible.builtin.get_url:
        url: "{{ go_download_base }}{{ go_tarball }}"
        dest: "/tmp/{{ go_tarball }}"
        mode: '0644'

    - name: Remove existing Go installation
      ansible.builtin.file:
        path: "{{ go_install_dir }}/go"
        state: absent

    - name: Extract Go tarball
      ansible.builtin.unarchive:
        src: "/tmp/{{ go_tarball }}"
        dest: "{{ go_install_dir }}"
        remote_src: yes

    - name: Set Go path in /etc/profile.d
      ansible.builtin.copy:
        content: |
          export PATH=$PATH:{{ go_install_dir }}/go/bin
        dest: /etc/profile.d/go.sh
        mode: '0644'

    - name: Clean up tarball
      ansible.builtin.file:
        path: "/tmp/{{ go_tarball }}"
        state: absent
