---
- name: Update Ubuntu and install Neovim
  hosts: localhost
  vars:
    desired_version: v0.11.3
  tasks:
    - name: Check nvim version
      command: nvim -v
      become: no
      ignore_errors: true
      register: nvim

    - name: Show facts available on the system
      ansible.builtin.debug:
        var: nvim

    - name: Extract semver
      ansible.builtin.set_fact:
        nvim_version: "{{ nvim.stdout_lines[0] | regex_search('v[0-9]+\\.[0-9]+\\.[0-9]+') }}"
      when: nvim.failed == false

    - name: Installed version
      debug:
        msg: "{{ nvim_version }}"
      when: nvim.failed == false

    - name: Continue?
      assert:
        that:
          - "nvim_version is version('desired_version', '<')"
      when: nvim.failed == false
      ignore_errors: yes

    - name: Update apt cache and upgrade packages
      apt:
        update_cache: yes
        upgrade: dist
        cache_valid_time: 3600
      become: yes

    - name: Install dependencies for Neovim
      apt:
        name:
          - git
          - build-essential
          - ninja-build
          - gettext
          - unzip
          - curl
          - tar
          - npm
        state: present
      become: yes

    - name: Download Neovim latest release
      get_url:
        url: "https://github.com/neovim/neovim/releases/latest/download/nvim-linux-{{ ISA }}.tar.gz"
        dest: "/tmp/nvim-linux-{{ ISA }}.tar.gz"
        mode: '0644'

    - name: Create /opt/nvim directory
      file:
        path: /opt/nvim
        state: directory
        mode: '0755'
      become: yes

    - name: Create /tmp/nvim-extracted directory
      file:
        path: /tmp/nvim-extracted
        state: directory
        mode: '0755'

    - name: Extract Neovim to /tmp for inspection
      unarchive:
        src: "/tmp/nvim-linux-{{ ISA }}.tar.gz"
        dest: /tmp/nvim-extracted
        creates: /tmp/nvim-extracted/nvim-linux-x86_64

    - name: "/tmp/nvim-extracted/nvim-linux-{{ ISA }} is empty?"
      shell: ls -lA
      args:
        chdir: "/tmp/nvim-extracted/nvim-linux-{{ ISA }}"
      register: contents

    - name: Remove previous version 
      ansible.builtin.file:
        path: "{{ item }}" 
        state: absent
      become: yes
      loop:
        - /opt/nvim
        - "{{ ansible_env.HOME }}/.config/nvim"

    - name: Move Neovim files to /opt/nvim
      shell: mv "/tmp/nvim-extracted/nvim-linux-{{ ISA }}/" /opt/nvim/
      when: contents["stdout_lines"] | length > 1 # total: 0 counts as 1
      become: yes

    - name: Ensure Neovim binary is executable
      file:
        path: /opt/nvim/bin/nvim
        mode: '0755'

    - name: Add Neovim to system-wide PATH
      lineinfile:
        path: /etc/profile.d/neovim.sh
        line: 'export PATH=$PATH:/opt/nvim/bin'
        create: yes
        mode: '0644'

    - name: Clone Neovim Kickstart config
      git:
        repo: https://github.com/nvim-lua/kickstart.nvim.git
        dest: "{{ ansible_env.HOME }}/.config/nvim"
        depth: 1

    - name: Set ownership of Neovim config
      file:
        path: "{{ ansible_env.HOME }}/.config/nvim"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        recurse: yes

    - name: Clean up downloaded tarball and extracted files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/tmp/nvim-linux-{{ ISA }}.tar.gz"
        - /tmp/nvim-extracted

    - name: Enable custom plugins in kickstart
      lineinfile:
        dest: "{{ ansible_env.HOME }}/.config/nvim/init.lua"
        regexp: "^  -- { import = 'custom.plugins' },$"
        line: " { import = 'custom.plugins' },"

    - name: Enable nerd fonts in kickstart
      lineinfile:
        dest: "{{ ansible_env.HOME }}/.config/nvim/init.lua"
        regexp: "^vim.g.have_nerd_font = false$"
        line: "vim.g.have_nerd_font = true"



